version: '3'

services:
  telegaf-python:
    build:
      context: ./Telegraf
      dockerfile: Dockerfile
    volumes:
      - ./Telegraf/checker.py:/app/checker.py
      - ./Telegraf/telegraf.conf:/etc/telegraf/telegraf.conf
    environment:
      - UNIQUE_TOKEN=UyUljOCvVPa1VBu5LbaAVLxy27tN5gz0
      - USERNAME=|>agent<|
      - INFLUX_TOKEN=|>token<|


