# Generated by Django 4.1.7 on 2023-04-11 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MonaApps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitorrequest',
            name='interval',
            field=models.SmallIntegerField(default='1'),
        ),
        migrations.AddField(
            model_name='monitorrequest',
            name='notification',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='monitorrequest',
            name='URL',
            field=models.URLField(),
        ),
    ]
