# Generated by Django 4.1.7 on 2023-04-11 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MonaApps', '0003_alter_monitorrequest_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MonitorRequest',
        ),
    ]
