# Generated by Django 4.1.7 on 2023-06-03 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MonaApps', '0006_token_old_tokens'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='generate_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
