# Generated by Django 4.1.7 on 2023-06-18 21:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MonaAppForm', '0002_monitorrequest_active_monitorrequest_expire_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitorrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 18, 21, 22, 49, 322323, tzinfo=datetime.timezone.utc)),
        ),
    ]
