# Generated by Django 4.1.7 on 2023-06-18 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MonaAppForm', '0003_alter_monitorrequest_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitorrequest',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
