# Generated by Django 4.1.7 on 2023-06-20 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MonaAppForm', '0004_alter_monitorrequest_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitorrequest',
            name='active',
        ),
        migrations.AddField(
            model_name='monitorrequest',
            name='terminated',
            field=models.BooleanField(default=False),
        ),
    ]
