version: '3'
services:
  influxdb:
    image: influxdb
    ports:
      - 8086:8086
    environment:
      - INFLUXDB_DB=mydb
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin

  grafana:
    image: grafana
    ports:
      - 3000:3000
    volumes:
      - ./custom.ini:/etc/grafana/grafana.ini
    depends_on:
      - influxdb
